regnetConfig:
  DEPTH: 13
  W0: 24
  WA: 36.44
  WM: 2.49
  GROUP_W: 8
  STRIDE: 2
  BOT_MUL: 1.0
  SE_RATIO: 0.25
  Q: 8
  STEM_IN: 3
  STEM_OUT: 32
  STEM_STRIDE: 2

biFPNConfig:
  NUM_LAYERS_BIFPN: 4
  NUM_CHANNELS_BIFPN: 128
  IN_CHANNELS: [24, 56, 152, 368, 368]

objectDetectionConfig:
  NUM_ANCHORS: 12
  NUM_LAYERS_DETECTION: 3
  NUM_CLASSES: 10
  NUM_CHANNELS_BIFPN: 128

segmentationConfig:
  NUM_FEATURES: 7 
  IN_CHANNELS: 128
  OUT_CHANNELS: 2
  STEM_IN_CHANNELS_LIST: [32, 32] # stem outputs
  WIDTH: 1280
  HEIGHT: 720
  ALPHA_LANE: 0.9
  ALPHA_ROAD: 0.7